version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: testcafe
    versions:
    - 1.10.1
    - 1.11.0
    - 1.12.0
    - 1.13.0
  - dependency-name: typescript
    versions:
    - 3.9.7
